package me.digi.sdk.models.music

import me.digi.sdk.models.AspectRatio
import me.digi.sdk.models.MediaResource
import me.digi.sdk.models.ModelParam
import me.digi.sdk.models.ModelTest

class ArtistSpec : ModelTest<Artist>(Artist::class.java, object : ModelParam<Artist> {
    override val emptyTest: Artist? = Artist(
            null,
            null,
            null,
            null,
            null
    )

    override val jsonObjectTests: List<Pair<Artist?, String>> =
            listOf(
                    Pair(
                            Artist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    setOf(
                                            MediaResource(
                                                    AspectRatio(1.5, "dummyActual", "dummyClosest"),
                                                    1,
                                                    2,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    3,
                                                    "dummyUrl"
                                            ),
                                            MediaResource(
                                                    AspectRatio(2.5, "dummyActual", "dummyClosest"),
                                                    4,
                                                    5,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    6,
                                                    "dummyUrl"
                                            )
                                    )
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[
                                        {
                                            "aspectratio":{
                                                "accuracy":1.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":1,
                                            "width":2,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":3,
                                            "url":"dummyUrl"
                                        },
                                        {
                                            "aspectratio":{
                                                "accuracy":2.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":4,
                                            "width":5,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":6,
                                            "url":"dummyUrl"
                                        }
                                    ]
                                }
                            """.trimIndent()
                    ),
                    Pair(
                            Artist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    setOf(
                                            MediaResource(
                                                    AspectRatio(1.5, "dummyActual", "dummyClosest"),
                                                    1,
                                                    2,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    3,
                                                    "dummyUrl"
                                            )
                                    )
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[
                                        {
                                            "aspectratio":{
                                                "accuracy":1.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":1,
                                            "width":2,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":3,
                                            "url":"dummyUrl"
                                        }
                                    ]
                                }
                            """.trimIndent()
                    ),
                    Pair(
                            Artist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    emptySet()
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[]
                                }
                            """.trimIndent()
                    )
            )

    override val jsonTests: List<Pair<Artist?, String>> =
            listOf(
                    Pair(
                            emptyTest,
                            """{"dummyType": "dummy"}"""
                    )
            )
})

class FollowedArtistSpec : ModelTest<FollowedArtist>(FollowedArtist::class.java, object : ModelParam<FollowedArtist> {
    override val emptyTest: FollowedArtist? = FollowedArtist(
            null,
            null,
            null,
            null,
            null
    )

    override val jsonObjectTests: List<Pair<FollowedArtist?, String>> =
            listOf(
                    Pair(
                            FollowedArtist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    setOf(
                                            MediaResource(
                                                    AspectRatio(1.5, "dummyActual", "dummyClosest"),
                                                    1,
                                                    2,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    3,
                                                    "dummyUrl"
                                            ),
                                            MediaResource(
                                                    AspectRatio(2.5, "dummyActual", "dummyClosest"),
                                                    4,
                                                    5,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    6,
                                                    "dummyUrl"
                                            )
                                    )
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[
                                        {
                                            "aspectratio":{
                                                "accuracy":1.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":1,
                                            "width":2,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":3,
                                            "url":"dummyUrl"
                                        },
                                        {
                                            "aspectratio":{
                                                "accuracy":2.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":4,
                                            "width":5,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":6,
                                            "url":"dummyUrl"
                                        }
                                    ]
                                }
                            """.trimIndent()
                    ),
                    Pair(
                            FollowedArtist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    setOf(
                                            MediaResource(
                                                    AspectRatio(1.5, "dummyActual", "dummyClosest"),
                                                    1,
                                                    2,
                                                    "application/dummyType",
                                                    "dummyResize",
                                                    3,
                                                    "dummyUrl"
                                            )
                                    )
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[
                                        {
                                            "aspectratio":{
                                                "accuracy":1.5,
                                                "actual":"dummyActual",
                                                "closest":"dummyClosest"
                                            },
                                            "height":1,
                                            "width":2,
                                            "mimetype":"application/dummyType",
                                            "resize":"dummyResize",
                                            "type":3,
                                            "url":"dummyUrl"
                                        }
                                    ]
                                }
                            """.trimIndent()
                    ),
                    Pair(
                            FollowedArtist(
                                    "dummyAccountEntityId",
                                    "dummyEntityId",
                                    "dummyId",
                                    "dummyName",
                                    emptySet()
                            ),
                            """
                                {
                                    "accountentityid":"dummyAccountEntityId",
                                    "entityid":"dummyEntityId",
                                    "id":"dummyId",
                                    "name":"dummyName",
                                    "resources":[]
                                }
                            """.trimIndent()
                    )
            )

    override val jsonTests: List<Pair<FollowedArtist?, String>> =
            listOf(
                    Pair(
                            emptyTest,
                            """{"dummyType": "dummy"}"""
                    )
            )
})